package tui

const (
	iconFile      = "󰈙"
	iconWorktree  = "󰙅"
	iconBranch    = ""
	iconModified  = ""
	iconAdded     = ""
	iconDeleted   = ""
	iconRenamed   = "󰁕"
	iconUntracked = ""
	iconBinary    = ""
	iconTheme     = ""
	iconQuit      = "󰩈"
	iconKey       = "󰌌"
	iconEdit      = ""
	iconWrap      = "󰖶"
	iconNumbers   = "󰎠"
	iconProtected = ""
	iconPR        = ""
	iconMerge     = ""
	iconStatus    = "󰎟"
	iconSelected  = "▸"
	iconToggleOn  = ""
	iconToggleOff = ""
	iconWarning   = ""
)
